// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQfCesKaSeSZETiahgqaPVW06_8TmK4BY',
    appId: '1:999331941249:web:e42587cf7fcac028097680',
    messagingSenderId: '999331941249',
    projectId: 'shopapp-42ad0',
    authDomain: 'shopapp-42ad0.firebaseapp.com',
    storageBucket: 'shopapp-42ad0.firebasestorage.app',
    measurementId: 'G-6JZ2S4SJ3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ6Xa817n4dwP1daUoJittpAuRLU26sVw',
    appId: '1:999331941249:android:c09ca8899eab67e1097680',
    messagingSenderId: '999331941249',
    projectId: 'shopapp-42ad0',
    storageBucket: 'shopapp-42ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsWvcViWCAkkJr9zsguL90YkabVQc1Z7U',
    appId: '1:999331941249:ios:39a429a8ef04adfa097680',
    messagingSenderId: '999331941249',
    projectId: 'shopapp-42ad0',
    storageBucket: 'shopapp-42ad0.firebasestorage.app',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsWvcViWCAkkJr9zsguL90YkabVQc1Z7U',
    appId: '1:999331941249:ios:39a429a8ef04adfa097680',
    messagingSenderId: '999331941249',
    projectId: 'shopapp-42ad0',
    storageBucket: 'shopapp-42ad0.firebasestorage.app',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQfCesKaSeSZETiahgqaPVW06_8TmK4BY',
    appId: '1:999331941249:web:2f8b627d09c8a2e0097680',
    messagingSenderId: '999331941249',
    projectId: 'shopapp-42ad0',
    authDomain: 'shopapp-42ad0.firebaseapp.com',
    storageBucket: 'shopapp-42ad0.firebasestorage.app',
    measurementId: 'G-SSDTLT4V2F',
  );
}
